#!/usr/bin/env bash

GREEN="\[\e[32m\]"
BLUE="\[\e[34m\]"
RED="\[\e[31m\]"
NC="\[\e[0m\]"

function branch_info {
    git branch > /dev/null 2>&1 
    if test $? -ne 0 ;then
        echo ""
    else
        echo "$(git rev-parse --abbrev-ref HEAD 2> /dev/null) "
    fi
    return 0
}

function prompt {
    if test $? -eq 0 ;then
        cs=$GREEN\$$NC
    else
        cs=$RED\$$NC
    fi
    bi=$BLUE$(branch_info)

    PS1="$GREEN\u@\h \W $bi$cs "
}

PROMPT_COMMAND=prompt
