#!/bin/bash

set -ueo pipefail

. $(dirname $0)/bin/steamcat.util.sh

function set_branch_info {
    if ! $(git branch > /dev/null 2>&1) ;then
        BRANCH=""
    else
        git_status="$(git status 2> /dev/null)"

        if [[ $git_status =~ "working directory clean" ]];then
            state="$GREEN"
        elif [[ $git_status =~ "Changes to be committed" ]];then
            state="$BLUE"
        else
            state="$RED"
        fi

        branch="$(git rev-parse --abbrev-ref HEAD 2> /dev/null)"

        BRANCH="$state$branch$NC "
    fi
}

function set_bash_prompt {
    if test $? -eq 0 ;then
        PROMPT_SYMBOL="$GREEN\$$NC"
    else 
        PROMPT_SYMBOL="$RED\$$NC"
    fi
    set_branch_info
    PS1="$COLOR_NONE\u@\h \W $BRANCH$PROMPT_SYMBOL "
}

PROMPT_COMMAND=set_bash_prompt
