#!/usr/bin/env bash

function branch_info {
    git branch > /dev/null 2>&1 
    if test $? -ne 0 ;then
        echo ""
    else
        echo "$(git rev-parse --abbrev-ref HEAD 2> /dev/null) "
    fi
    return 0
}

function prompt {
    if test $? -eq 0 ;then
        cs="\033[0;32m\$\033[0m"
    else
        cs="\033[0;31m\$\033[0m"
    fi
    bi=$(branch_info)

    PS1="\033[0;32m\u@\h \W \033[1;34m$bi$cs "
}

PROMPT_COMMAND=prompt
